### ISSUE TITLE
aurbs domain down

### ISSUE THREAD

**Issue by darkgeem** [unixfox/aur#18]
the domain aurbs.unixfox.eu does not lead anywhere anymore, is that normal?
and if it is, could you tell us the reason or at least upload the links in the readme.md please? :)

**Comment by unixfox** [comment]
I used the free plan of AWS to host AurBS, and they throttled it so hard after a few months that it was nearly impossible to build any AUR package.
So I took it down, waiting to find another server. I haven't really think about it until today.
I may bring back on the AUR build server because I found about the free plan of Oracle a week ago and it seems that their VPS are powerful enough to build most of the AUR packages.

**Comment by unixfox** [comment]
Up again!
